<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Form Cuti_mui-p-10084-T-infoCuti</name>
   <tag></tag>
   <elementGuidId>fbd09afe-2715-485b-881d-ed067555a2aa</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#mui-p-10084-T-infoCuti</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='mui-p-10084-T-infoCuti']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=tab[name=&quot;Info Cuti&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>fcb902a3-c17b-49c0-ba88-4cbe4d9c416b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>MuiButtonBase-root MuiTab-root MuiTab-textColorPrimary css-1sh52gn</value>
      <webElementGuid>70efcf99-b226-44b4-861e-397e8c871fb3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>-1</value>
      <webElementGuid>9c030b27-38a3-4fc3-9fe2-49bd882de5dd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>fc071e0f-ed2d-4efd-bf44-23641365a710</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>tab</value>
      <webElementGuid>812f36a0-00d3-4dc6-9713-d33964db0d06</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-selected</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>f3142c5c-168d-45ce-8d4f-2c2ba8c17324</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-controls</name>
      <type>Main</type>
      <value>mui-p-10084-P-infoCuti</value>
      <webElementGuid>a191fffb-c9db-4335-9d58-f025a41eeb81</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>mui-p-10084-T-infoCuti</value>
      <webElementGuid>70a381a0-bbcf-4520-9fcc-90966136d177</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Info Cuti</value>
      <webElementGuid>cd3986a8-5028-45fa-87c0-a297b4175053</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;mui-p-10084-T-infoCuti&quot;)</value>
      <webElementGuid>db651a4f-499a-4a93-ba31-a17440b09919</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@id='mui-p-10084-T-infoCuti']</value>
      <webElementGuid>4414ba06-3bfc-48ac-b5fa-0574ef8b77e6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Form Cuti'])[1]/following::button[1]</value>
      <webElementGuid>8291d6e9-eca6-42bd-b7d9-16beba9a6e66</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Pilih Tipe Cuti'])[1]/preceding::button[1]</value>
      <webElementGuid>53f45adf-3dc4-4247-8d3b-6bc08a6c3c31</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Pilih Tipe Absen'])[1]/preceding::button[1]</value>
      <webElementGuid>cb81f52d-9aff-48c3-ace0-39f18fda9cdc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Info Cuti']/parent::*</value>
      <webElementGuid>9b085847-8373-4b60-91a4-099851cd7cdb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//button[2]</value>
      <webElementGuid>329ca7bf-40b6-4cf3-bf09-52a245cb0872</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@type = 'button' and @id = 'mui-p-10084-T-infoCuti' and (text() = 'Info Cuti' or . = 'Info Cuti')]</value>
      <webElementGuid>ce6e18d7-3174-48fc-8370-aab80a2a2ec6</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
