<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img</name>
   <tag></tag>
   <elementGuidId>9ea94891-e867-4896-b4fb-26236a24f117</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='__next']/div/div/div/div[3]/div/div/div[3]/div/div/a/div/span/img</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>img[alt=&quot;Izin&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>a >> internal:has-text=&quot;Izin&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>509dadd4-4bb2-422b-bd95-0f5f32fa2409</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>alt</name>
      <type>Main</type>
      <value>Izin</value>
      <webElementGuid>a242a0ba-b7dc-42a0-8d88-674f6711ea90</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>sizes</name>
      <type>Main</type>
      <value>100vw</value>
      <webElementGuid>1c2714cf-0bb0-4fd4-bd81-b5bee477b3bd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>srcset</name>
      <type>Main</type>
      <value>/_next/image?url=%2Fstatic%2Fimages%2Ficons%2Fizin.svg&amp;w=640&amp;q=75 640w, /_next/image?url=%2Fstatic%2Fimages%2Ficons%2Fizin.svg&amp;w=750&amp;q=75 750w, /_next/image?url=%2Fstatic%2Fimages%2Ficons%2Fizin.svg&amp;w=828&amp;q=75 828w, /_next/image?url=%2Fstatic%2Fimages%2Ficons%2Fizin.svg&amp;w=1080&amp;q=75 1080w, /_next/image?url=%2Fstatic%2Fimages%2Ficons%2Fizin.svg&amp;w=1200&amp;q=75 1200w, /_next/image?url=%2Fstatic%2Fimages%2Ficons%2Fizin.svg&amp;w=1920&amp;q=75 1920w, /_next/image?url=%2Fstatic%2Fimages%2Ficons%2Fizin.svg&amp;w=2048&amp;q=75 2048w, /_next/image?url=%2Fstatic%2Fimages%2Ficons%2Fizin.svg&amp;w=3840&amp;q=75 3840w</value>
      <webElementGuid>98b9acad-c350-4a2b-81dd-c6c763d7ae26</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>/_next/image?url=%2Fstatic%2Fimages%2Ficons%2Fizin.svg&amp;w=3840&amp;q=75</value>
      <webElementGuid>2d558ba3-d86a-4c2a-ba2d-cad26aa19b29</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>decoding</name>
      <type>Main</type>
      <value>async</value>
      <webElementGuid>a121f6c2-7aa8-4db2-b08a-37ac54cf43f8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-nimg</name>
      <type>Main</type>
      <value>responsive</value>
      <webElementGuid>1a8ed298-531f-4e84-bf24-dae09ad92729</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;__next&quot;)/div[@class=&quot;MuiBox-root css-0&quot;]/div[@class=&quot;MuiContainer-root MuiContainer-maxWidthSm css-ewqxmf&quot;]/div[@class=&quot;MuiBox-root css-19n8dai&quot;]/div[@class=&quot;MuiBox-root css-wmurvm&quot;]/div[@class=&quot;MuiBox-root css-1dovkig&quot;]/div[@class=&quot;MuiGrid-root MuiGrid-container MuiGrid-spacing-xs-2 css-isbt42&quot;]/div[@class=&quot;MuiGrid-root MuiGrid-item MuiGrid-grid-xs-3 MuiGrid-grid-sm-3 css-4xkoi8&quot;]/div[@class=&quot;MuiBox-root css-7wh13m&quot;]/div[@class=&quot;MuiBox-root css-zg1vud&quot;]/a[@class=&quot;user__menu__item&quot;]/div[@class=&quot;MuiBox-root css-11uwjng&quot;]/span[1]/img[1]</value>
      <webElementGuid>4275bc15-7144-444a-8192-8044c2dc221e</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='__next']/div/div/div/div[3]/div/div/div[3]/div/div/a/div/span/img</value>
      <webElementGuid>48ddf0ba-22a6-44be-8d1c-f701ddf2efe3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>//img[@alt='Izin']</value>
      <webElementGuid>ff42e532-44b3-460d-92f0-2cdb9985870f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/div/a/div/span/img</value>
      <webElementGuid>fc84e1ac-bf85-4215-9690-eb7043f01fc7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@alt = 'Izin' and @src = '/_next/image?url=%2Fstatic%2Fimages%2Ficons%2Fizin.svg&amp;w=3840&amp;q=75']</value>
      <webElementGuid>648b7491-c3c0-4106-9c43-7b7eaff3cce0</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
