<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>ul_Ajukan_mui-4</name>
   <tag></tag>
   <elementGuidId>27a81f75-0d16-4a54-a9b2-40029d8a97de</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#mui-4</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//ul[@id='mui-4']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:text=&quot;Pilih Tipe AbsenKhitanan/Pembabtisan (2 hari) Pernikahan anak (2 hari) Cuti pers&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>ul</value>
      <webElementGuid>c46867f5-f063-43fe-b3c1-0fb8362b4081</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>MuiList-root MuiList-padding MuiMenu-list css-r8u8y9</value>
      <webElementGuid>347e085d-108d-4506-b067-6a3f93efb37c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>listbox</value>
      <webElementGuid>8a2dbc99-0e5a-4a5f-8ca3-b01edd28aedd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>-1</value>
      <webElementGuid>b4fccebc-ba2d-4ab6-8825-21eb3025f0c6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>mui-4</value>
      <webElementGuid>5467cbf2-ac08-4c2d-911a-5e2e8f2db61e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Pilih Tipe AbsenKhitanan/Pembabtisan (2 hari) Pernikahan anak (2 hari) Cuti persalinan (3 bulan) Cuti berduka saudara kandung/keluarga yang tinggal satu rumah (1 hari)Cuti berduka orang tua,anak,suami/istri,mertua (2 hari)Pernikahan anak(1 hari)Pernikahan diri sendiri (3 hari)Cuti Tahunan</value>
      <webElementGuid>d0b84bf9-6b8a-4b6a-b668-c7ecb6447faf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;mui-4&quot;)</value>
      <webElementGuid>0cc9a83e-df4f-4991-9186-d6922d41a7aa</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//ul[@id='mui-4']</value>
      <webElementGuid>7d82b43b-3538-4afe-95fc-f75404fedc4c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='menu-leave_type_id']/div[3]/ul</value>
      <webElementGuid>665c9953-e29f-4d83-8e9c-ef5bee3b26a4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Ajukan'])[1]/following::ul[1]</value>
      <webElementGuid>0a1a8093-4858-470d-8dd4-1590c785abee</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Reset'])[1]/following::ul[1]</value>
      <webElementGuid>89c409ce-c750-4b2c-8b52-a0961828eb23</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//ul</value>
      <webElementGuid>5b073998-632f-441d-b068-8df71a98c37b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//ul[@id = 'mui-4' and (text() = 'Pilih Tipe AbsenKhitanan/Pembabtisan (2 hari) Pernikahan anak (2 hari) Cuti persalinan (3 bulan) Cuti berduka saudara kandung/keluarga yang tinggal satu rumah (1 hari)Cuti berduka orang tua,anak,suami/istri,mertua (2 hari)Pernikahan anak(1 hari)Pernikahan diri sendiri (3 hari)Cuti Tahunan' or . = 'Pilih Tipe AbsenKhitanan/Pembabtisan (2 hari) Pernikahan anak (2 hari) Cuti persalinan (3 bulan) Cuti berduka saudara kandung/keluarga yang tinggal satu rumah (1 hari)Cuti berduka orang tua,anak,suami/istri,mertua (2 hari)Pernikahan anak(1 hari)Pernikahan diri sendiri (3 hari)Cuti Tahunan')]</value>
      <webElementGuid>a8a2add2-7f22-4f39-b037-ede4911d0175</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
