<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>p__selfie-helper-text</name>
   <tag></tag>
   <elementGuidId>34159c69-8e23-470e-b9ca-e226c896d5fc</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//p[@id='selfie-helper-text']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#selfie-helper-text</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:text=&quot;*File harus berupa file Excel (.xls atau .xlsx)&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>p</value>
      <webElementGuid>b8c51950-999e-4489-bf93-76ada4d90156</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>MuiFormHelperText-root Mui-error MuiFormHelperText-sizeSmall MuiFormHelperText-contained MuiFormHelperText-filled Mui-required css-a13hsf</value>
      <webElementGuid>7bdebe7b-0c80-4abb-b193-fd582238a8aa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>selfie-helper-text</value>
      <webElementGuid>935c09b7-618e-4525-a6fa-e460c0185a9c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>*File harus berupa file Excel (.xls atau .xlsx)</value>
      <webElementGuid>e24f3baa-d4fb-4825-b3ad-67bad03f8a75</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;selfie-helper-text&quot;)</value>
      <webElementGuid>d586a7a0-57ab-4208-b8be-b52f46ae10ab</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//p[@id='selfie-helper-text']</value>
      <webElementGuid>a76f9a49-161b-43d4-a9ba-8f5b0dce1239</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='__next']/div/div[2]/div/div/div/div/div/form/div[2]/div/div/div/p</value>
      <webElementGuid>3e70cffd-cfa2-41ba-a456-a188bd594224</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='​'])[1]/following::p[1]</value>
      <webElementGuid>08b6b6dd-b009-4355-b99f-a5cd5a23c4f9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Import Excel Status Aktif'])[1]/following::p[1]</value>
      <webElementGuid>af77aa6a-6be6-4bfa-934f-127b5c4de804</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Import'])[2]/preceding::p[1]</value>
      <webElementGuid>f1e12320-2d0d-4bdd-87cf-ba650d2d1335</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Download Template'])[1]/preceding::p[1]</value>
      <webElementGuid>116ce21b-255c-4136-9f26-57f7e91fa85b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='*File harus berupa file Excel (.xls atau .xlsx)']/parent::*</value>
      <webElementGuid>3d862f64-1976-4fb8-80ac-3489b4eaabd7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//form/div[2]/div/div/div/p</value>
      <webElementGuid>418f8cab-21c5-4ad4-9923-3135b987a9ef</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//p[@id = 'selfie-helper-text' and (text() = '*File harus berupa file Excel (.xls atau .xlsx)' or . = '*File harus berupa file Excel (.xls atau .xlsx)')]</value>
      <webElementGuid>5aca71db-eb74-44b8-8bef-ea1f87cb36c1</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
